Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/smith/git/FortyTwoTestTask-1/fortytwo_test_task/urls.py", line 10, in <module>
    url(r'^', include('apps.hello.urls', namespace="hello")),
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/urls.py", line 11, in <module>
    url(r'^request_list_ajax/$', views.request_list_ajax,
AttributeError: 'module' object has no attribute 'request_list_ajax'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/middleware.py", line 12, in process_request
    return save_request.save()
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/signals.py", line 12, in post_save_signal
    LogEntrry.objects.create(title=sender.__name__, status='Create')
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: hello_logentrry
Internal Server Error: /request_list/
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/views.py", line 35, in request_list
    return render(request, 'hello/request_list.html', context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 304, in render
    if match:
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/query.py", line 100, in __nonzero__
    self._fetch_all()
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such column: hello_requests.priority
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/middleware.py", line 12, in process_request
    return save_request.save()
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table hello_requests has no column named priority
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/middleware.py", line 12, in process_request
    return save_request.save()
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table hello_requests has no column named priority
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/middleware.py", line 12, in process_request
    return save_request.save()
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: hello_requests.priority
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/middleware.py", line 12, in process_request
    return save_request.save()
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: hello_requests.priority
Internal Server Error: /update_profile/
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/views.py", line 48, in update_profile
    form.save()
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/forms/models.py", line 446, in save
    construct=False)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/forms/models.py", line 99, in save_instance
    instance.save()
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/models.py", line 37, in save
    imagefit.save(self.photo.path, 'JPEG', quality=75)
AttributeError: 'NoneType' object has no attribute 'save'
Internal Server Error: /admin/hello/profile/1/
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 452, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1250, in change_view
    self.save_model(request, new_object, form, True)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 880, in save_model
    obj.save()
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/models.py", line 37, in save
    imagefit.save(self.photo.path, 'JPEG', quality=75)
AttributeError: 'NoneType' object has no attribute 'save'
Internal Server Error: /update_profile/
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/views.py", line 48, in update_profile
    form.save()
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/forms/models.py", line 446, in save
    construct=False)
  File "/home/smith/.virtualenvs/test/local/lib/python2.7/site-packages/django/forms/models.py", line 99, in save_instance
    instance.save()
  File "/home/smith/git/FortyTwoTestTask-1/apps/hello/models.py", line 38, in save
    imagefit.save(self.photo.path, 'JPEG', quality=75)
AttributeError: 'NoneType' object has no attribute 'save'
